<?php
/**
 * XBuilder Workflow Test
 *
 * Tests the complete workflow:
 * 1. AI generates code with proper format
 * 2. HTML is extracted correctly
 * 3. Preview is saved
 * 4. Publish works
 * 5. Site is accessible at root domain
 */

require_once __DIR__ . '/xbuilder/core/Security.php';
require_once __DIR__ . '/xbuilder/core/Config.php';
require_once __DIR__ . '/xbuilder/core/AI.php';
require_once __DIR__ . '/xbuilder/core/Generator.php';
require_once __DIR__ . '/xbuilder/core/Conversation.php';

use XBuilder\Core\AI;
use XBuilder\Core\Generator;
use XBuilder\Core\Conversation;

echo "🧪 XBuilder Workflow Test\n";
echo str_repeat("=", 50) . "\n\n";

// Test 1: HTML Extraction
echo "1️⃣  Testing HTML Extraction...\n";

$testHtml = <<<'HTML'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Portfolio</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-900 text-white">
    <h1 class="text-4xl font-bold">Test Portfolio</h1>
    <p>This is a test website generated by XBuilder.</p>
</body>
</html>
HTML;

// Simulate AI response with code block
$aiResponse = <<<RESPONSE
I've created a beautiful portfolio website for you! Here's what I built:

The design features a modern dark theme with clean typography and smooth animations.

```xbuilder-html
$testHtml
```

Check the Preview tab to see your website! When you're happy with it, click 'Publish to Live Site' to deploy.
RESPONSE;

// Use reflection to test private extractHtml method
$ai = new AI('claude'); // Provider doesn't matter for extraction test
$reflection = new ReflectionClass($ai);
$method = $reflection->getMethod('extractHtml');
$method->setAccessible(true);

$extractedHtml = $method->invoke($ai, $aiResponse);

if ($extractedHtml) {
    echo "   ✅ HTML extracted successfully (" . strlen($extractedHtml) . " chars)\n";
    echo "   ✅ Contains DOCTYPE: " . (str_contains($extractedHtml, '<!DOCTYPE html>') ? 'YES' : 'NO') . "\n";
    echo "   ✅ Contains closing </html>: " . (str_contains($extractedHtml, '</html>') ? 'YES' : 'NO') . "\n";
} else {
    echo "   ❌ FAILED: No HTML extracted!\n";
    echo "   Debug: Response length = " . strlen($aiResponse) . " chars\n";
    exit(1);
}

echo "\n";

// Test 2: Generator - Save Preview
echo "2️⃣  Testing Preview Save...\n";

$generator = new Generator();
$previewSaved = $generator->savePreview($extractedHtml);

if ($previewSaved) {
    echo "   ✅ Preview saved to: " . $generator->getPreviewPath() . "\n";
    echo "   ✅ Preview file exists: " . (file_exists($generator->getPreviewPath()) ? 'YES' : 'NO') . "\n";
} else {
    echo "   ❌ FAILED: Could not save preview\n";
    exit(1);
}

echo "\n";

// Test 3: Publish to Live Site
echo "3️⃣  Testing Publish to Live Site...\n";

$result = $generator->saveHtml($extractedHtml, 'index.html');

if ($result['success']) {
    echo "   ✅ Published to: " . $result['path'] . "\n";
    echo "   ✅ File size: " . $result['size'] . " bytes\n";
    echo "   ✅ Public URL: " . $result['url'] . "\n";
    echo "   ✅ File exists: " . (file_exists($result['path']) ? 'YES' : 'NO') . "\n";
} else {
    echo "   ❌ FAILED: " . $result['error'] . "\n";
    exit(1);
}

echo "\n";

// Test 4: Verify HTML Structure
echo "4️⃣  Validating Published HTML...\n";

$errors = $generator->validateHtml($extractedHtml);

if (empty($errors)) {
    echo "   ✅ HTML structure is valid\n";
} else {
    echo "   ⚠️  Validation warnings:\n";
    foreach ($errors as $error) {
        echo "      - $error\n";
    }
}

echo "\n";

// Test 5: Check Accessibility
echo "5️⃣  Checking Site Accessibility...\n";

$indexPath = $generator->getIndexPath();
$siteDir = dirname($indexPath);
$webRoot = dirname($siteDir);

echo "   📁 Site directory: $siteDir\n";
echo "   📁 Web root: $webRoot\n";
echo "   📄 Index file: $indexPath\n";

if (file_exists($indexPath)) {
    $content = file_get_contents($indexPath);
    echo "   ✅ Site is published and accessible\n";
    echo "   ✅ Published size: " . strlen($content) . " bytes\n";

    // Check if it matches what we published
    if ($content === $extractedHtml) {
        echo "   ✅ Published content matches generated HTML\n";
    } else {
        echo "   ⚠️  Published content differs from generated HTML\n";
    }
} else {
    echo "   ❌ FAILED: Index file not found!\n";
    exit(1);
}

echo "\n";

// Test 6: System Prompt Check
echo "6️⃣  Checking AI System Prompt...\n";

$reflection = new ReflectionClass($ai);
$method = $reflection->getMethod('getSystemPrompt');
$method->setAccessible(true);
$systemPrompt = $method->invoke($ai);

$hasInterfaceSection = str_contains($systemPrompt, 'THE XBUILDER INTERFACE');
$mentionsPreviewTab = str_contains($systemPrompt, 'Preview tab');
$mentionsPublishButton = str_contains($systemPrompt, 'Publish to Live Site');
$warnsAgainstManual = str_contains($systemPrompt, 'NEVER tell users');

echo "   ✅ Has interface explanation: " . ($hasInterfaceSection ? 'YES' : 'NO') . "\n";
echo "   ✅ Mentions Preview tab: " . ($mentionsPreviewTab ? 'YES' : 'NO') . "\n";
echo "   ✅ Mentions Publish button: " . ($mentionsPublishButton ? 'YES' : 'NO') . "\n";
echo "   ✅ Warns against manual copy/paste: " . ($warnsAgainstManual ? 'YES' : 'NO') . "\n";

echo "\n";

// Summary
echo str_repeat("=", 50) . "\n";
echo "✅ ALL TESTS PASSED!\n\n";

echo "📝 Summary:\n";
echo "   • HTML extraction: WORKING\n";
echo "   • Preview save: WORKING\n";
echo "   • Publish to live site: WORKING\n";
echo "   • HTML validation: WORKING\n";
echo "   • Site accessibility: WORKING\n";
echo "   • AI understands interface: WORKING\n";

echo "\n";
echo "🌐 Your test site is now accessible at:\n";
echo "   http://yourdomain.com/\n";
echo "   (or the root URL of where XBuilder is installed)\n";

echo "\n";
echo "📌 Next Steps:\n";
echo "   1. Visit your domain to see the test site\n";
echo "   2. Try creating a real site through /xbuilder/\n";
echo "   3. Upload a CV/DOCX file\n";
echo "   4. Ask AI to build a portfolio\n";
echo "   5. Check Preview tab\n";
echo "   6. Click 'Publish to Live Site'\n";

echo "\n";
